---
title: "Altitude Performance Modeling"
author: "Derek Rogers"
date: "2023-01-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(ggplot2)
```

Read in the data and clean it
```{r}
circuitsDataFrame = read.csv("C:/SMU MS Data Science/AppliedStatistics6372/Project1/F1ParametricModeling/Data/circuits.csv")
constructorResultsDataFrame = read.csv("C:/SMU MS Data Science/AppliedStatistics6372/Project1/F1ParametricModeling/Data/constructor_results.csv")
constructorStandingsDataFrame = read.csv("C:/SMU MS Data Science/AppliedStatistics6372/Project1/F1ParametricModeling/Data/constructor_standings.csv")
constructorsDataFrame = read.csv("C:/SMU MS Data Science/AppliedStatistics6372/Project1/F1ParametricModeling/Data/constructors.csv")
driverStandingsDataFrame = read.csv("C:/SMU MS Data Science/AppliedStatistics6372/Project1/F1ParametricModeling/Data/driver_standings.csv")
driversDataFrame = read.csv("C:/SMU MS Data Science/AppliedStatistics6372/Project1/F1ParametricModeling/Data/drivers.csv")
lapTimesDataFrame = read.csv("C:/SMU MS Data Science/AppliedStatistics6372/Project1/F1ParametricModeling/Data/lap_times.csv")
pitStopsDataFrame = read.csv("C:/SMU MS Data Science/AppliedStatistics6372/Project1/F1ParametricModeling/Data/pit_stops.csv")
qualifyingDataFrame = read.csv("C:/SMU MS Data Science/AppliedStatistics6372/Project1/F1ParametricModeling/Data/qualifying.csv")
racesDataFrame = read.csv("C:/SMU MS Data Science/AppliedStatistics6372/Project1/F1ParametricModeling/Data/races.csv")
resultsDataFrame = read.csv("C:/SMU MS Data Science/AppliedStatistics6372/Project1/F1ParametricModeling/Data/results.csv")
seasonsDataFrame = read.csv("C:/SMU MS Data Science/AppliedStatistics6372/Project1/F1ParametricModeling/Data/seasons.csv")
sprint_resultsDataFrame = read.csv("C:/SMU MS Data Science/AppliedStatistics6372/Project1/F1ParametricModeling/Data/sprint_results.csv")
statusDataFrame = read.csv("C:/SMU MS Data Science/AppliedStatistics6372/Project1/F1ParametricModeling/Data/status.csv")

# Fill in the 2 missing altitudes
circuitsDataFrame[circuitsDataFrame$name == "Losail International Circuit",]$alt = 14
circuitsDataFrame[circuitsDataFrame$name == "Miami International Autodrome",]$alt = 1

# Convert altitude from character to numeric
circuitsDataFrame$alt = as.numeric(circuitsDataFrame$alt)
```

Keep relevant columns for creating a dataframe that holds relevant information for modeling
```{r}
racesDataFrame = subset(racesDataFrame, select = c("raceId", "year", "circuitId", "name"))

resultsDataFrame = subset(resultsDataFrame, select = c("resultId", "raceId", "driverId", "constructorId", "grid", "positionOrder"))

circuitsDataFrame = subset(circuitsDataFrame, select = c("circuitId", "name", "alt"))

constructorsDataFrame = subset(constructorsDataFrame, select = c("constructorId", "name"))
```

Merge relevant data into raceResultsDataframe
```{r}
raceResultsDataFrame = merge(x = racesDataFrame, y = resultsDataFrame, by = "raceId")

raceResultsDataFrame = merge(x = raceResultsDataFrame, y = circuitsDataFrame, by = "circuitId")

raceResultsDataFrame = merge(x = raceResultsDataFrame, y = constructorsDataFrame, by = "constructorId")

raceResultsDataFrame
```

# Show the number of times constructors appear in the raceResultsDataframe and keep the 10 most popular constructors
```{r}
uniqueConstructorResults = raceResultsDataFrame %>% group_by(name) %>% tally()

uniqueConstructorResults$n = as.numeric(uniqueConstructorResults$n)

uniqueConstructorResults = uniqueConstructorResults[order(-uniqueConstructorResults$n),]

#uniqueConstructorResults

uniqueConstructorResults = head(uniqueConstructorResults, 10)

uniqueConstructorResults
```

Only keep race results from the 5 most popular constructors
```{r}
raceResultsDataFrame = raceResultsDataFrame %>% filter(raceResultsDataFrame$name == uniqueConstructorResults$name)
raceResultsDataFrame
```

```{r}
ggplot(raceResultsDataFrame, aes(x = alt, y = positionOrder, color = name)) +
  geom_point(position = "jitter") +
  geom_smooth(method = lm)
```

```{r}
model = lm(positionOrder ~ alt + name + alt:name, data = raceResultsDataFrame)

summary(model)
```